name: newgraduate
description: "تطبيق خريج للدورات التعليمية"
publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  youtube_player_iframe: ^5.2.2
  youtube_player_flutter: ^9.1.2
  # pod_player removed (replaced by webview-based player)
  lottie: ^3.1.0
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.2.2
  device_info_plus: ^10.1.2
  geolocator: ^10.1.0
  crypto: ^3.0.3
  path_provider: ^2.1.2
  webview_flutter: ^4.4.2
  screen_capture_event: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/
    
  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: fonts/NotoKufiArabic-Regular.ttf
        - asset: fonts/NotoKufiArabic-Bold.ttf
          weight: 700
